### PR TITLE
Fix typo in breaking.md

### PR DESCRIPTION
**Pull request by ota-meshi**

### CODE REVIEW

**Comment by ota-meshi** [comment]
I mistake.

**Comment by ota-meshi** [comment]
Hmm. I didn't make a mistake.

**Comment by ota-meshi** [comment]
We maybe also need to fix the `<i18n-n>` documentation.

**Comment by ota-meshi** [comment]
I've never used the tag omission feature, but as far as I can see in the docs, I think the fix is correct.

**Review by kazupon — APPROVED** [review]
Thank you for you feedback!

Yeah, You're right!
The following v8.x code:
https://github.com/kazupon/vue-i18n/blob/bc4c62d7f6c8e4ebb2139d2e55e414e4db69a69b/src/components/interpolation.js#L43-L44

**Pull request merged**
