### PR TITLE
fix(types): allow spyOn of "useI18n()"

### LINKED ISSUE #1562: Typing regression on "useI18n()": spyOn return "never" type
### Reporting a bug?

After upgrade from `9.3.0-beta.27`, the mock of `useI18n()` doesn't work:
```typescript
import * as vueI18n from 'vue-i18n'

vi.spyOn(vueI18n, 'useI18n').mockReturnValue({})
```
throws
`Property 'mockReturnValue' does not exist on type 'never'.`

### Expected behavior

No error :)

### Reproduction

1. Create TypeScript project
2. `npm install vue-i118n`
3. Add a simple test  
    ```typescript
    import { vi } from 'vitest'
    import * as vueI18n from 'vue-i18n'
    vi.spyOn(vueI18n, 'useI18n').mockReturnValue({})
    ````
4. `npm run type-check`

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 10.91 GB / 31.69 GB
  Binaries:
    Node: 20.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.5.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (117.0.2045.36)
    Internet Explorer: 11.0.22621.1
```

### Screenshot

_No response_

### Additional context

Seems be a regression in #1309 https://github.com/intlify/vue-i18n-next/commit/7ebb0e4f69658ea76237bc24ff3e9e8b722063ec#diff-90783ef144f3a897c890355ff61bd08a99bbd36764128426b6f899a72e766f2eR803

Reverting line to previous version `NonNullable<Options['locale']>` seems fix the problem.
Like the `test:type` checks are still OK, probably the current typing is too strict? 🤔 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

### PR DESCRIPTION
**Pull request by pinguet62**
Try fix #1562

### CODE REVIEW

**Review by kazupon — CHANGES_REQUESTED** [review]
Thank you for your contribution!

However, I think #1304 is broken with your PR, your PR has regression. 
https://github.com/intlify/vue-i18n-next/issues/1304

Can you please suggest another solution, please?

**Comment by pinguet62** [comment]
Hello @kazupon

I tested this case, and I don't see any regression:
```typescript
expectType<string>(useI18n().locale.value)
expectType<string>(useI18n({useScope: 'local'}).locale.value)
```
(typing tests already added in #1309)

Please could you give any `expectType()` example breaking #1304 ?

**Review by kazupon — APPROVED** [review]
sorry, I missed the test of #1309
LGTM

**Comment by pinguet62** [comment]
Many thanks! Have a nice day 🖖

**Pull request merged**
